Astro-Slide:
  - '(astroslide|Astro Slide|astro slide|Astro|astro)'

Cosmo-Communicator:
  - '(cosmocom|Cosmo Communicator|cosmo communicator|Cosmo|cosmo|codi|CoDi|cover display|Cover Display|external display|external screen)'

Gemini-PDA:
  - '(geminipda|Gemini PDA|gemini pda|Gemini)'

Android-FW:
  - '(Android|android)'

Sound-Issue:
  - '(Speaker|speaker|Audio|audio|Phase|phase)'

Gemian-FW:
  - '(Gemian|gemian|debian|Debian|buster|Buster|bullseye|Bullseye)'
